name: CI

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta


jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USERNAME}}

           
        run: |
          echo "GitHub Event: $GITHUB_EVENT_NAME"
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "GitHub Ref: $GITHUB_REF"
          echo "GitHub Actor: $GITHUB_ACTOR"
          echo "SSH Private Key: $PRIVATE_KEY"
          echo "EC2 Hostname: $HOSTNAME"
          echo "EC2 Username: $USER_NAME"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              cd /home/ubuntu/<PROJECT_DIRECTORY> &&
              git pull origin beta
              '
