name: CI

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/private_key.pem && chmod 600 $HOME/.ssh/private_key.pem

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: $HOME/.ssh/private_key.pem

      - name: Deploy to EC2 Development
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/bundleAPI/development && git pull origin beta"

